version: "3.8"

services:
  web:
    image: odoo
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - DB_HOST=mydb
      - DB_USER=odoo
      - DB_PASSWORD=myodoo
      - DB_NAME=odoodb  # Optional, but good if you created a custom DB in Postgres

  mydb:
    image: postgres
    environment:
      - POSTGRES_DB=odoodb
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
